name: noise_cutter
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - torchaudio==2.6.0+cu124
      - opencv-python
      - numpy
      - scipy
      - pillow
      - yt-dlp
      - python-dotenv
      - imagehash==4.3.1
      - PyWavelets==1.4.1
variables:
  KMP_DUPLICATE_LIB_OK: "TRUE"